# Generated by Django 5.1.3 on 2024-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_comida_descripcion_alter_comida_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
